import { Config } from "../types/fullscreen";

export const DEFAULTS: Config = {
    def: {
        lyricsDisplay: true,
        thirdPartyLyrics: true,
        sharedLyricsBridge: true,
        relaxedLyricsMatching: false,
        showLyricsTranslation: true,
        showLyricsRomanization: true,
        showLyricsFurigana: true,
        lyricsChineseConversion: "original",
        karaokeLyrics: true,
        lyricsSize: 42,
        autoHideLyrics: true,
        debugMode: false,
        progressBarDisplay: "always",
        playerControls: "always",
        trimTitle: true,
        trimTitleUpNext: true,
        trimAlbum: false,
        showAlbum: "date",
        icons: false,
        titleMovingIcon: false,
        enableFullscreen: true,
        upnextDisplay: "smart",
        themedButtons: true,
        themedIcons: false,
        invertColors: "never",
        backAnimationTime: 1,
        animationSpeed: 0.25,
        beatBounce: true,
        beatResponsePreset: "medium",
        bpmDrivenMotion: true,
        beatScaleAmount: 0.18,
        beatWarpAmount: 0.08,
        beatSaturationAmount: 0.2,
        beatSpeedAmount: 0.2,
        beatAttack: 0.8,
        beatRelease: 0.08,
        upnextTimeToShow: 30,
        blurSize: 32,
        backgroundBrightness: 0.7,
        verticalMonitorSupport: true,
    },
    locale: "en-US",
    fsHideOriginal: false,
    autoLaunch: "never",
    activationTypes: "both",
    autoUpdateCheck: true,
};
