import { Config } from "../types/fullscreen";

export const DEFAULTS: Config = {
    def: {
        lyricsDisplay: true,
        thirdPartyLyrics: true,
        showLyricsTranslation: true,
        showLyricsRomanization: true,
        karaokeLyrics: true,
        lyricsSize: 30,
        autoHideLyrics: true,
        progressBarDisplay: "always",
        playerControls: "always",
        trimTitle: true,
        trimTitleUpNext: true,
        trimAlbum: false,
        showAlbum: "date",
        icons: false,
        titleMovingIcon: false,
        enableFullscreen: true,
        backgroundChoice: "album_art",
        upnextDisplay: "smart",
        themedButtons: true,
        themedIcons: false,
        invertColors: "never",
        backAnimationTime: 1,
        animationSpeed: 0.25,
        upnextTimeToShow: 30,
        coloredBackChoice: "DESATURATED",
        staticBackChoice: "#787878",
        blurSize: 32,
        backgroundBrightness: 0.7,
        verticalMonitorSupport: true,
    },
    locale: "en-US",
    fsHideOriginal: false,
    autoLaunch: "never",
    activationTypes: "both",
};
